# Form implementation generated from reading ui file 'create.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CreateAccountFrame(object):
    def setupUi(self, CreateAccountFrame):
        CreateAccountFrame.setObjectName("CreateAccountFrame")
        CreateAccountFrame.resize(622, 371)
        CreateAccountFrame.setMinimumSize(QtCore.QSize(622, 371))
        CreateAccountFrame.setMaximumSize(QtCore.QSize(100000, 100000))
        CreateAccountFrame.setStyleSheet("background-color: rgb(24, 20, 20);")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=CreateAccountFrame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(160, 120, 281, 131))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.create_password = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.create_password.setStyleSheet("background-color: rgb(20, 216, 92);")
        self.create_password.setObjectName("create_password")
        self.gridLayout.addWidget(self.create_password, 1, 0, 1, 1)
        self.create_name_line = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.create_name_line.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.create_name_line.setText("")
        self.create_name_line.setObjectName("create_name_line")
        self.gridLayout.addWidget(self.create_name_line, 0, 1, 1, 1)
        self.create_name = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.create_name.setStyleSheet("background-color: rgb(20, 216, 92);")
        self.create_name.setObjectName("create_name")
        self.gridLayout.addWidget(self.create_name, 0, 0, 1, 1)
        self.create_password_line = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.create_password_line.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.create_password_line.setObjectName("create_password_line")
        self.gridLayout.addWidget(self.create_password_line, 1, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.create_back_button = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.create_back_button.setStyleSheet("background-color: rgb(20, 216, 92);")
        self.create_back_button.setObjectName("create_back_button")
        self.horizontalLayout.addWidget(self.create_back_button)
        self.create_account_button = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.create_account_button.setStyleSheet("background-color: rgb(20, 216, 92);")
        self.create_account_button.setObjectName("create_account_button")
        self.horizontalLayout.addWidget(self.create_account_button)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 1, 1, 1)

        self.retranslateUi(CreateAccountFrame)
        QtCore.QMetaObject.connectSlotsByName(CreateAccountFrame)

    def retranslateUi(self, CreateAccountFrame):
        _translate = QtCore.QCoreApplication.translate
        CreateAccountFrame.setWindowTitle(_translate("CreateAccountFrame", "CREATE ACCOUNT"))
        self.create_password.setText(_translate("CreateAccountFrame", "Password"))
        self.create_name.setText(_translate("CreateAccountFrame", "Username"))
        self.create_back_button.setText(_translate("CreateAccountFrame", "Back"))
        self.create_account_button.setText(_translate("CreateAccountFrame", "Create"))
