# Form implementation generated from reading ui file 'editaccount.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EditAccount(object):
    def setupUi(self, EditAccount):
        EditAccount.setObjectName("EditAccount")
        EditAccount.resize(622, 371)
        EditAccount.setMinimumSize(QtCore.QSize(622, 371))
        EditAccount.setMaximumSize(QtCore.QSize(100000, 100000))
        EditAccount.setStyleSheet("background-color: rgb(24, 20, 20);")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=EditAccount)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(150, 100, 331, 171))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.edit_username = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.edit_username.setStyleSheet("background-color: rgb(20, 216, 92);")
        self.edit_username.setObjectName("edit_username")
        self.gridLayout.addWidget(self.edit_username, 0, 0, 1, 1)
        self.new_username = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.new_username.setStyleSheet("background-color: rgb(20, 216, 92);")
        self.new_username.setObjectName("new_username")
        self.gridLayout.addWidget(self.new_username, 2, 0, 1, 1)
        self.edit_username_line = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.edit_username_line.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.edit_username_line.setText("")
        self.edit_username_line.setObjectName("edit_username_line")
        self.gridLayout.addWidget(self.edit_username_line, 0, 1, 1, 1)
        self.new_username_line = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.new_username_line.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.new_username_line.setObjectName("new_username_line")
        self.gridLayout.addWidget(self.new_username_line, 2, 1, 1, 1)
        self.edit_password_line = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.edit_password_line.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.edit_password_line.setObjectName("edit_password_line")
        self.gridLayout.addWidget(self.edit_password_line, 1, 1, 1, 1)
        self.edit_password = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.edit_password.setStyleSheet("background-color: rgb(20, 216, 92);")
        self.edit_password.setObjectName("edit_password")
        self.gridLayout.addWidget(self.edit_password, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.edit_acc_back = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.edit_acc_back.setStyleSheet("background-color: rgb(20, 216, 92);")
        self.edit_acc_back.setObjectName("edit_acc_back")
        self.horizontalLayout.addWidget(self.edit_acc_back)
        self.edit_acc_confirm = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.edit_acc_confirm.setStyleSheet("background-color: rgb(20, 216, 92);")
        self.edit_acc_confirm.setObjectName("edit_acc_confirm")
        self.horizontalLayout.addWidget(self.edit_acc_confirm)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 1, 1, 1)
        self.new_password = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.new_password.setStyleSheet("background-color: rgb(20, 216, 92);")
        self.new_password.setObjectName("new_password")
        self.gridLayout.addWidget(self.new_password, 3, 0, 1, 1)
        self.new_password_line = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.new_password_line.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.new_password_line.setObjectName("new_password_line")
        self.gridLayout.addWidget(self.new_password_line, 3, 1, 1, 1)

        self.retranslateUi(EditAccount)
        QtCore.QMetaObject.connectSlotsByName(EditAccount)

    def retranslateUi(self, EditAccount):
        _translate = QtCore.QCoreApplication.translate
        EditAccount.setWindowTitle(_translate("EditAccount", "Edit Account"))
        self.edit_username.setText(_translate("EditAccount", "Verify Username"))
        self.new_username.setText(_translate("EditAccount", "Enter New Username"))
        self.edit_password.setText(_translate("EditAccount", "Verify Password"))
        self.edit_acc_back.setText(_translate("EditAccount", "Back"))
        self.edit_acc_confirm.setText(_translate("EditAccount", "Confirm"))
        self.new_password.setText(_translate("EditAccount", "Enter New Password"))
