# Form implementation generated from reading ui file 'import.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ImportMusic(object):
    def setupUi(self, ImportMusic):
        ImportMusic.setObjectName("ImportMusic")
        ImportMusic.resize(622, 371)
        ImportMusic.setStyleSheet("background-color: rgb(24, 20, 20);")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=ImportMusic)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(160, 110, 301, 142))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.import_title = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.import_title.setStyleSheet("background-color: rgb(20, 216, 92);")
        self.import_title.setObjectName("import_title")
        self.gridLayout.addWidget(self.import_title, 0, 0, 1, 1)
        self.import_artist_line = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.import_artist_line.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.import_artist_line.setObjectName("import_artist_line")
        self.gridLayout.addWidget(self.import_artist_line, 1, 1, 1, 1)
        self.import_duration_line = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.import_duration_line.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.import_duration_line.setObjectName("import_duration_line")
        self.gridLayout.addWidget(self.import_duration_line, 2, 1, 1, 1)
        self.import_duration = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.import_duration.setStyleSheet("background-color: rgb(20, 216, 92);")
        self.import_duration.setObjectName("import_duration")
        self.gridLayout.addWidget(self.import_duration, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.import_back_button = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.import_back_button.setStyleSheet("background-color: rgb(20, 216, 92);")
        self.import_back_button.setObjectName("import_back_button")
        self.horizontalLayout.addWidget(self.import_back_button)
        self.import_confirm_button = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.import_confirm_button.setStyleSheet("background-color: rgb(20, 216, 92);")
        self.import_confirm_button.setObjectName("import_confirm_button")
        self.horizontalLayout.addWidget(self.import_confirm_button)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 1, 1, 1)
        self.import_title_line = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.import_title_line.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.import_title_line.setObjectName("import_title_line")
        self.gridLayout.addWidget(self.import_title_line, 0, 1, 1, 1)
        self.import_artist = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.import_artist.setStyleSheet("background-color: rgb(20, 216, 92);")
        self.import_artist.setObjectName("import_artist")
        self.gridLayout.addWidget(self.import_artist, 1, 0, 1, 1)
        self.select_file_button = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.select_file_button.setStyleSheet("background-color: rgb(20, 216, 92);")
        self.select_file_button.setObjectName("select_file_button")
        self.gridLayout.addWidget(self.select_file_button, 3, 0, 1, 1)
        self.select_file_line = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.select_file_line.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.select_file_line.setObjectName("select_file_line")
        self.gridLayout.addWidget(self.select_file_line, 3, 1, 1, 1)

        self.retranslateUi(ImportMusic)
        QtCore.QMetaObject.connectSlotsByName(ImportMusic)

    def retranslateUi(self, ImportMusic):
        _translate = QtCore.QCoreApplication.translate
        ImportMusic.setWindowTitle(_translate("ImportMusic", "IMPORT MUSIC"))
        self.import_title.setText(_translate("ImportMusic", "Music Title"))
        self.import_duration.setText(_translate("ImportMusic", "Duration(HH:MM:SS)"))
        self.import_back_button.setText(_translate("ImportMusic", "Back"))
        self.import_confirm_button.setText(_translate("ImportMusic", "Confirm"))
        self.import_artist.setText(_translate("ImportMusic", "Artist"))
        self.select_file_button.setText(_translate("ImportMusic", "Select File"))
