# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Login_Window(object):
    def setupUi(self, Login_Window):
        Login_Window.setObjectName("Login_Window")
        Login_Window.resize(622, 371)
        Login_Window.setMinimumSize(QtCore.QSize(622, 371))
        Login_Window.setMaximumSize(QtCore.QSize(100000, 100000))
        Login_Window.setStyleSheet("background-color: rgb(18, 18, 18);")
        self.centralwidget = QtWidgets.QWidget(parent=Login_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(160, 120, 281, 131))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.login_password = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.login_password.setStyleSheet("background-color: rgb(20, 216, 92);")
        self.login_password.setObjectName("login_password")
        self.gridLayout.addWidget(self.login_password, 1, 0, 1, 1)
        self.login_name_line = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.login_name_line.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.login_name_line.setText("")
        self.login_name_line.setObjectName("login_name_line")
        self.gridLayout.addWidget(self.login_name_line, 0, 1, 1, 1)
        self.login_name = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.login_name.setStyleSheet("background-color: rgb(20, 216, 92);")
        self.login_name.setObjectName("login_name")
        self.gridLayout.addWidget(self.login_name, 0, 0, 1, 1)
        self.login_password_line = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.login_password_line.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.login_password_line.setObjectName("login_password_line")
        self.gridLayout.addWidget(self.login_password_line, 1, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.create_account_button = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.create_account_button.setStyleSheet("background-color: rgb(20, 216, 92);")
        self.create_account_button.setObjectName("create_account_button")
        self.horizontalLayout.addWidget(self.create_account_button)
        self.login_button = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.login_button.setStyleSheet("background-color: rgb(20, 216, 92);")
        self.login_button.setObjectName("login_button")
        self.horizontalLayout.addWidget(self.login_button)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 1, 1, 1)
        Login_Window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=Login_Window)
        self.statusbar.setObjectName("statusbar")
        Login_Window.setStatusBar(self.statusbar)

        self.retranslateUi(Login_Window)
        QtCore.QMetaObject.connectSlotsByName(Login_Window)

    def retranslateUi(self, Login_Window):
        _translate = QtCore.QCoreApplication.translate
        Login_Window.setWindowTitle(_translate("Login_Window", "LOGIN"))
        self.login_password.setText(_translate("Login_Window", "Password"))
        self.login_name.setText(_translate("Login_Window", "Username"))
        self.create_account_button.setText(_translate("Login_Window", "Create Account"))
        self.login_button.setText(_translate("Login_Window", "Login"))
